### PR TITLE
Bugfix site switch error and missing site handle on index page

### PR DESCRIPTION
**Pull request by pdaleramirez**
Fixed (#54)

### CODE REVIEW

**Comment by angrybrad** [comment]
@pdaleramirez I'm getting exexpected behavior when testing this. On a multi-site install, if I enter content into the Title for a Digital Product type on site 2, it looks like that content is saved on site 1 and site 1's title is pulled into site 2. Can you verify?

**Comment by peirix** [comment]
Does this mean we should hold off on getting the latest version on `dev-develop`?

**Comment by stevenjwright** [comment]
@pdaleramirez @angrybrad hey guys, what's the latest on this? This one's currently a bit of a road block for us at the moment. 

Cheers!

**Comment by pdaleramirez** [comment]
> @pdaleramirez I'm getting unexpected behavior when testing this. On a multi-site install, if I enter content into the Title for a Digital Product type on site 2, it looks like that content is saved on site 1 and site 1's title is pulled into site 2. Can you verify?

It is a bug indeed. I've included the fix on the pull request. The product should be saving on the selected site now.

**Review by nfourtythree — APPROVED** [review]
Merged in `develop`, tested and tweaked the changelog. Everything looks good and worked as expected.

Will get this merged.

**Pull request merged**
